
export const skillIcons = {
  core: [
    { name: "JavaScript", icon: "javascript", color: "F7DF1E" },
    { name: "TypeScript", icon: "typescript", color: "3178C6" },
    { name: "Python", icon: "python", color: "3776AB" },
    { name: "Java", icon: "java", color: "007396" },
    { name: "C++", icon: "cplusplus", color: "00599C" },
    { name: "Go", icon: "go", color: "00ADD8" },
    { name: "Rust", icon: "rust", color: "000000" },
    { name: "PHP", icon: "php", color: "777BB4" },
    { name: "Ruby", icon: "ruby", color: "CC342D" },
    { name: "Swift", icon: "swift", color: "F05138" },
    { name: "Kotlin", icon: "kotlin", color: "7F52FF" },
    { name: "C#", icon: "csharp", color: "239120" },
    { name: "Dart", icon: "dart", color: "0175C2" },
  ],
  frontend: [
    { name: "React", icon: "react", color: "61DAFB" },
    { name: "Next.js", icon: "nextdotjs", color: "000000" },
    { name: "Vue.js", icon: "vuedotjs", color: "4FC08D" },
    { name: "Angular", icon: "angular", color: "DD0031" },
    { name: "Svelte", icon: "svelte", color: "FF3E00" },
    { name: "TailwindCSS", icon: "tailwindcss", color: "06B6D4" },
    { name: "Bootstrap", icon: "bootstrap", color: "7952B3" },
    { name: "HTML5", icon: "html5", color: "E34F26" },
    { name: "CSS3", icon: "css3", color: "1572B6" },
    { name: "Sass", icon: "sass", color: "CC6699" },
    { name: "Redux", icon: "redux", color: "764ABC" },
    { name: "Webpack", icon: "webpack", color: "8DD6F9" },
  ],
  backend: [
    { name: "Node.js", icon: "nodedotjs", color: "339933" },
    { name: "Express", icon: "express", color: "000000" },
    { name: "NestJS", icon: "nestjs", color: "E0234E" },
    { name: "Django", icon: "django", color: "092E20" },
    { name: "Flask", icon: "flask", color: "000000" },
    { name: "Spring Boot", icon: "springboot", color: "6DB33F" },
    { name: "GraphQL", icon: "graphql", color: "E10098" },
    { name: "Laravel", icon: "laravel", color: "FF2D20" },
    { name: "FastAPI", icon: "fastapi", color: "009688" },
  ],
  database: [
    { name: "PostgreSQL", icon: "postgresql", color: "4169E1" },
    { name: "MySQL", icon: "mysql", color: "4479A1" },
    { name: "MongoDB", icon: "mongodb", color: "47A248" },
    { name: "Redis", icon: "redis", color: "DC382D" },
    { name: "SQLite", icon: "sqlite", color: "003B57" },
    { name: "Firebase", icon: "firebase", color: "FFCA28" },
    { name: "Supabase", icon: "supabase", color: "3ECF8E" },
    { name: "Oracle", icon: "oracle", color: "F80000" },
  ],
  devops: [
    { name: "Docker", icon: "docker", color: "2496ED" },
    { name: "Kubernetes", icon: "kubernetes", color: "326CE5" },
    { name: "AWS", icon: "amazonaws", color: "232F3E" },
    { name: "Google Cloud", icon: "googlecloud", color: "4285F4" },
    { name: "Azure", icon: "microsoftazure", color: "0078D4" },
    { name: "GitHub Actions", icon: "githubactions", color: "2088FF" },
    { name: "Jenkins", icon: "jenkins", color: "D24939" },
    { name: "Terraform", icon: "terraform", color: "7B42BC" },
    { name: "Linux", icon: "linux", color: "FCC624" },
    { name: "Nginx", icon: "nginx", color: "009639" },
  ],
  tools: [
    { name: "Git", icon: "git", color: "F05032" },
    { name: "Figma", icon: "figma", color: "F24E1E" },
    { name: "Postman", icon: "postman", color: "FF6C37" },
    { name: "VS Code", icon: "visualstudiocode", color: "007ACC" },
    { name: "Vim", icon: "vim", color: "019733" },
    { name: "Unity", icon: "unity", color: "000000" },
    { name: "Unreal Engine", icon: "unrealengine", color: "0E1128" },
  ]
};
